# Week4　授業前課題3　オブジェクト指向の活用  
これまでの課題では触れてきませんでしたが、``StandardScaler``や``LinearRegression``のような **クラス** と呼ばれるものがPythonなどのプログラム言語では利用できます。
クラスの構文は、オブジェクト指向と呼ばれる考え方を利用したプログラミングの基本的な道具になります。
この課題ではこれまでに既に登場していたクラスを例に、クラスを活用することでどのようなことができるのかを見て学んでいきます。そして課題の後半では``StandardScaler``のクラスをスクラッチで自作します。

### 【問題1】これまで利用してきたクラスの列挙  
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。
Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

1. Pandas
  - DataFrame
  - Series
2. mtplotlib
  - pyplot
  - patches
3. scikit-learn
  - LogistcRegression
  - LinearRegression
など

### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙  
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。
最低でもそれぞれ5つ以上答えてください。

1. メソッド
   - .transform()
   - .predict()
   - .info()
   - .describe()
   - .isnull() など
2. インスタンス変数
   - columns_
   - index_
   - dtypes_
   - coef_
   - intercept_ など

### 【問題3】標準化クラスをスクラッチで作成  
理解をより深めるため、``StandardScaler``をスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的には``fit``メソッドと``transform``メソッドを作ります。
今回は雛形を用意しました。クラスの作成方法は関数に近いです。メソッドはクラスの中にさらにインデントを一段下げて記述します。
インスタンス変数を作成する際は``self.mean_``のように``self``を付けます。クラスの外から``scaler.mean_``と書いていたscalerの部分が自分自身を表すselfになっています。

In [79]:
# 標準化スクラッチ
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """    
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
    
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / self.var_**(1/2)
        return X_scaled


In [81]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
print("X = %s\n" % X)
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}\n".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print("X_std = %s" % X_std)

X = [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]

X_std = [[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


#### ＜特殊メソッド＞
ソースコードの中に含まれる、``__init__``というメソッドは、どのクラスにも共通して置かれる **コンストラクタ** と呼ばれるメソッドです。  
コンストラクタの動作を確認するためのサンプルコードを用意しました。コンストラクタは、インスタンス化が行われる時に自動的に実行されるという働きがあります。こういった特殊な動作をするメソッドを、 **特殊メソッド** と呼びます。

In [82]:
# サンプルコード
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


### 【問題4】四則演算を行うクラスの作成  
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。
クラス名や説明文も適切に書き換えてください。

In [83]:
# 四則演算
class ArthmeticOperations():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        if type(self.value) != int and type(self.value) != float:
            print("演算は定義できません")
        else:
            print("初期値{}が設定されました".format(self.value))
    
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        if type(value2) != int and type(value2) != float:
            print("和は定義できません")
        else:
            self.value += value2
    
    def subtract(self, value2):
        """
        受け取った引数をself.valueから引く
        """
        if type(value2) != int and type(value2) != float:
            print("差は定義できません")
        else:
            self.value -= value2
    
    def multiply(self, value2):
        """
        受け取った引数をself.valueに掛ける
        """
        if type(value2) != int and type(value2) != float:
            print("積は定義できません")
        else:
            self.value *= value2
    
    def devide(self, value2):
        """
        受け取った引数でself.valueを割る
        """
        if type(value2) != int and type(value2) != float:
            print("商は定義できません")
        elif value2 == 0:
            print("0の商は定義できません")
        else:
            self.value /= value2 

        
example = ArthmeticOperations(5)
example2 = ArthmeticOperations('5')

print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.add('3')
print("value : {}".format(example.value))

example.subtract(3)
print("value : {}".format(example.value))
example.subtract('3')
print("value : {}".format(example.value))

example.multiply(3)
print("value : {}".format(example.value))
example.multiply('3')
print("value : {}".format(example.value))

example.devide(3)
print("value : {}".format(example.value))
example.devide('3')
print("value : {}".format(example.value))
example.devide(0)
print("value : {}".format(example.value))

初期値5が設定されました
演算は定義できません
value : 5
value : 8
和は定義できません
value : 8
value : 5
差は定義できません
value : 5
value : 15
積は定義できません
value : 15
value : 5.0
商は定義できません
value : 5.0
0の商は定義できません
value : 5.0
